SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";



 CREATE TABLE BOOK
(
EDITION VARCHAR(20),
B_ISBN INTEGER PRIMARY KEY,
CATEGORY VARCHAR(20),
PUB_YEAR VARCHAR(20),
TITLE VARCHAR(20),
PUB_NAME VARCHAR(20),
AVAILABLE INTEGER,
AUTHOR_NAME VARCHAR(20),
FOREIGN KEY AUTHOR_NAME REFERENCES BOOK_AUTHORS(AUTHOR_NAME)
);
 
CREATE TABLE USER
(

U_ID INTEGER PRIMARY KEY,
U_NAME VARCHAR(20),
ADDRESS VARCHAR(20),
U_PHONE VARCHAR(10),
FINES INTEGER,
EXP_DATE DATE,
B_ISBN INTEGER,
FOREIGN KEY (B_ISBN) REFERENCES BOOK(B_ISBN) ON DELETE CASCADE
);

CREATE TABLE LIBRARIAN
(
LIB_ID INTEGER PRIMARY KEY,
LIB_NAME VARCHAR(20),
LIB_PHONE VARCHAR(10)
);

CREATE TABLE BOOK_COPIES
(
NO_OF_COPIES INTEGER,
B_ISBN INTEGER,
FOREIGN KEY(B_ISBN)REFERENCES BOOK(B_ISBN) ON DELETE CASCADE
);



CREATE TABLE AUTHENTICATION_SYSTEM
(
PASSWORDS VARCHAR(10),
U_ID INTEGER,
LIB_ID INTEGER,
FOREIGN KEY(U_ID)REFERENCES USER(U_ID) ON DELETE CASCADE,
FOREIGN KEY(LIB_ID)REFERENCES LIBRARIAN(LIB_ID) ON DELETE CASCADE
);



INSERT INTO LIBRARIAN (LIB_ID,LIB_NAME,LIB_PHONE)
(1,'Sarah','6361147087'
);
ALTER TABLE AUTHENTICATION_SYSTEM 
 ADD FOREIGN KEY (LIB_ID)
    REFERENCES LIBRARIAN(LIB_ID)  
    ON DELETE CASCADE
    ON UPDATE CASCADE;

INSERT INTO AUTHENTICATION_SYSTEM(PASSWORDS,LIB_ID)
('12345678','1');